export const STATES_BR = [
    { id: 1, value: "AC", text: "Acre" },
    { id: 2, value: "AL", text: "Alagoas" },
    { id: 3, value: "AM", text: "Amapá" },
    { id: 4, value: "AM", text: "Amazonas" },
    { id: 5, value: "BA", text: "Bahia" },
    { id: 6, value: "CE", text: "Ceará" },
    { id: 7, value: "DF", text: "Distrito Federal" },
    { id: 8, value: "ES", text: "Espirito Santo" },
    { id: 9, value: "GO", text: "Goiás" },
    { id: 10, value: "MA", text: "Maranhão" },
    { id: 11, value: "MS", text: "Mato Grosso do Sul" },
    { id: 12, value: "MT", text: "Mato Grosso" },
    { id: 13, value: "MG", text: "Minas Gerais" },
    { id: 14, value: "PA", text: "Pará" },
    { id: 15, value: "PB", text: "Paraíba" },
    { id: 16, value: "PE", text: "Pernambuco" },
    { id: 17, value: "PI", text: "Piauí" },
    { id: 18, value: "RJ", text: "Rio de Janeiro" },
    { id: 19, value: "RN", text: "Rio Grande do Norte" },
    { id: 20, value: "RS", text: "Rio Grande do Sul" },
    { id: 21, value: "RO", text: "Rondônia" },
    { id: 22, value: "RR", text: "Roraima" },
    { id: 23, value: "SC", text: "Santa Catarina" },
    { id: 24, value: "SP", text: "São Paulo" },
    { id: 25, value: "SE", text: "Sergipe" },
    { id: 26, value: "TO", text: "Tocantins" },
]